### ISSUE TITLE
Generated code tries to extend an interface. TS2689

### ISSUE THREAD

**Issue by jonasmercelis** [microsoft/kiota-typescript#1040]
# Summary  
Generated code by the Kiota dotnet tool (1.10.1) tries to extend the interface 'BaseRequestBuilder'.

## Environment info
Platform: macOS Sonoma 14.3 (23D56) ARM64
node v20.10.0  
npm 10.3.0  
kiota dotnet tool version: 1.10.1+fa5da75b8b4f362d821032021bc5bfcf063cb522
dotnet SDK: 8.0.101 (arm64)

## Steps to reproduce
The ['Build API clients for TypeScript' Quickstart](https://learn.microsoft.com/en-us/openapi/kiota/quickstarts/typescript) instructions were used.

`npm init
npm install -D typescript ts-node
npx tsc --init`

**The following dependencies are added:**  
kiota-abstractions: ^1.0.0-preview.37
kiota-http-fetchlibrary: ^1.0.0-preview.36
kiota-serialization-form: ^1.0.0-preview.26
kiota-serialization-json: ^1.0.0-preview.37
kiota-serialization-multipart: ^1.0.0-preview.16
kiota-serialization-text: ^1.0.0-preview.34

posts-api.yml was used 

Followed by the following command:  
`kiota generate -l typescript -d posts-api.yml -c PostsClient -o ./client. `

Then, the index.ts file from the quickstart was used.

## Actual result

Running `npx ts-node index.ts` resulted in the following error:

```
<redacted>/tempdir/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
client/postsClient.ts:14:34 - error TS2689: Cannot extend an interface 'BaseRequestBuilder'. Did you mean 'implements'?

14 export class PostsClient extends BaseRequestBuilder<PostsClient> {
                                    ~~~~~~~~~~~~~~~~~~
client/postsClient.ts:19:45 - error TS2339: Property 'pathParameters' does not exist on type 'PostsClient'.

19         return new PostsRequestBuilder(this.pathParameters, this.requestAdapter);
                                               ~~~~~~~~~~~~~~
client/postsClient.ts:19:66 - error TS2339: Property 'requestAdapter' does not exist on type 'PostsClient'.

19         return new PostsRequestBuilder(this.pathParameters, this.requestAdapter);
                                                                    ~~~~~~~~~~~~~~
client/postsClient.ts:26:50 - error TS7006: Parameter 'x' implicitly has an 'any' type.

26         super({}, requestAdapter, "{+baseurl}", (x, y) => new PostsClient(y));
                                                    ~
client/postsClient.ts:26:53 - error TS7006: Parameter 'y' implicitly has an 'any' type.

26         super({}, requestAdapter, "{+baseurl}", (x, y) => new PostsClient(y));
                                                       ~
client/postsClient.ts:37:14 - error TS2339: Property 'pathParameters' does not exist on type 'PostsClient'.

37         this.pathParameters["baseurl"] = requestAdapter.baseUrl;
```

**Comment by baywet** [comment]
Hi @jonasmercelis 
Thanks for using kiota and for reaching out.
TypeScript still being an experimental language for kiota, we often ship breaking changes. This will not be the case once typescript becomes a stable language.

This is caused because we released updates to the typescript packages yesterday, and the corresponding changes haven't been released for the generator.
You can either:
- wait until thursday afternoon for the next preview of kiota which will have those changes.
- install the correct versions of the typescript dependencies (`kiota info -l typescript` will give you the details)
