### ISSUE TITLE
Add support for Enums or collection of enum values as root of the payload

### ISSUE THREAD

**Issue by baywet** [microsoft/kiota-typescript#1042]
A good example of that is beta `POST /deviceManagement/chromeOSOnboardingSettings/disconnect` which returns `chromeOSOnboardingStatus` (enum)

Here are the changes we need to make:
1. Request adapter interface need to accept objects as well for the responseType argument of the "sendPrimitiveAsync" and "sendCollectionOfPrimitiveAsync" methods
2. reflect the changes to the implementation
3. add a case in the implementation to call getEnumValue/getCollectionOfEnumValues when an object is provided.
4. update kiota generation to use that method for enums, add a using to the Object of the enum, and pass that object (in CodeConstantWriter for the requests metadata constants)

+ required tests

**Comment by andrueastman** [comment]
> 1. Request adapter interface need to accept objects as well for the responseType argument of the "sendPrimitiveAsync" and "sendCollectionOfPrimitiveAsync" methods

Just to confirm here that we should use "sendPrimitiveAsync" and "sendCollectionOfPrimitiveAsync" or align with other langs to add `sendEnumAsync` and `sendCollectionOfEnumsAsync`. 

cc @baywet

**Comment by baywet** [comment]
I think it'd make more sense to align with the other languages to be specific about what's expected from the implementations.
Especially with the reasoning you've provided here https://github.com/microsoft/kiota-abstractions-dotnet/issues/199
