### ISSUE TITLE
MultiPart Request Error

### ISSUE THREAD

**Issue by p30arena** [microsoft/kiota-typescript#1068]
The MultiPart body is malformed, the string value contains an additional **\r\n** and the server doesn't accept it when the values are validated.
Also, when uploading a file, "filename" is required by Django, but there is no way to provide additional keys and values to the message part.

**Comment by baywet** [comment]
Hi @p30arena 
Thanks for using kiota and for reporting that.
I can see you've already started a PR, so I'll head over there to provide feedback.

**Comment by bugproof** [comment]
Same problem with ASP.NET Core... `IFormFile` is `null` and server doesn't accept it

**Comment by atigirb** [comment]
> Same problem with ASP.NET Core and all the other web frameworks I guess... `IFormFile` is `null` and server doesn't accept it. I wasted 1+ hour looking for the solution and it was kiota serialization code fault. This bug is critical as it completely makes kiota clients useless for file uploads. I just used `FormData` and `fetch` as a workaround and much simpler too...

This issue seems to be happening due to missing file name in content disposition. 
Added it inside the partName in addorReplacePart and seems to work. At least when only one file is being added.
But would be great to have an actual fix. 
```
const body = new MultipartBody();
body.addOrReplacePart(`file"; filename="${file.fileName}`, file.contentType, file.content);
```
