### ISSUE TITLE
Polymorphism of buffer usage

### ISSUE THREAD

**Issue by baywet** [microsoft/kiota-typescript#1072]
The libraries here make use of Buffer.from multiple places
https://github.com/microsoft/kiota-typescript/blob/dfaf4045855f358a44f1fa91b5b85da901b5d24e/packages/authentication/azure/src/azureIdentityAccessTokenProvider.ts#L85
https://github.com/microsoft/kiota-typescript/blob/dfaf4045855f358a44f1fa91b5b85da901b5d24e/packages/serialization/json/src/jsonParseNode.ts#L59
https://github.com/microsoft/kiota-typescript/blob/dfaf4045855f358a44f1fa91b5b85da901b5d24e/packages/serialization/json/src/jsonSerializationWriter.ts#L19
https://github.com/microsoft/kiota-typescript/blob/dfaf4045855f358a44f1fa91b5b85da901b5d24e/packages/serialization/text/src/textParseNode.ts#L31
https://github.com/microsoft/kiota-typescript/blob/dfaf4045855f358a44f1fa91b5b85da901b5d24e/packages/serialization/text/src/textSerializationWriter.ts#L20

This API is NOT AVAILABLE on browsers, we're using it to perform base64 encoding/decoding.

We should instead:
- define two base64 encode/decode methods in abstractions
- in the implementations test whether Buffer.from is available, if so, use that.
- in the implementations test whether atob/btoa are available, if so, use that.
- if none of those APIs are available, throw
- replace the calls to Buffer.from by the corresponding method.

**Comment by musale** [comment]
Adding this to fixes https://github.com/microsoft/kiota-typescript/blob/cd0b0ba50d70e92df22ee1ffe204d95306156073/packages/abstractions/test/common/requestInformation.ts#L9 as url is also a nodejs API in the test usage and fails browser tests.

**Comment by sebastienlevert** [comment]
@musale are you still working on this and still have time? This is blocking for public preview and we might need to re-assign to make progress. Please let us know!

**Comment by petrhollayms** [comment]
Yep, confirmed with @musale today

**Comment by musale** [comment]
@sebastienlevert @petrhollayms almost done with this. Fixing the conflicts and final touches based on https://github.com/microsoft/kiota-typescript/blob/main/packages/http/fetch/docs/design/isomorphic.md as I move over to ESM. I'll have an update on Monday.
