### ISSUE TITLE
 couldn't find navigation property then data: "{+baseurl}"

### ISSUE THREAD

**Issue by jimmywim** [microsoft/kiota-typescript#1075]
Just fired up a new project I'm working on, and decided to bring kiota into the mix.

Updated the dotnet tool to 1.11.1, and the generated client is now throwing this error:

```
REDACTED.tsx:138  Error: couldn't find navigation property then data: "{+baseurl}"
    at Object.get (apiClientProxifier.ts:394:15)
```

The call is occurring after the call to the function that creates the client.

The bottom of the generated client class has this line:

```
/**
 * Uri template for the request builder.
 */
export const REDACTEDClientUriTemplate = "{+baseurl}";
```

Which is the third parameter passed into the `apiClientProxifier` function.

Have tried abstractions version 1.0.0-preview.40 (suggested by the dotnet tool recommendation) and 1.0.0-preview.43 (current at time of writing).

**Comment by baywet** [comment]
Thanks for using kiota and for reaching out.
Typescript is still an experimental language at this point and missalignments like those might happen as we work to stabilize the language.
Can you please:
1. Make sure you have the latest of all Kiota dependencies
1. Re-generate the client from the preview version of Kiota that came out yesterday

**Comment by jimmywim** [comment]
Thanks for getting back.

I've updated kiota to `1.11.1-preview.202402150001` and the depdencies to:

```
    "@microsoft/kiota-abstractions": "^1.0.0-preview.43",
    "@microsoft/kiota-authentication-azure": "^1.0.0-preview.38",
    "@microsoft/kiota-http-fetchlibrary": "^1.0.0-preview.42",
    "@microsoft/kiota-serialization-form": "^1.0.0-preview.32",
    "@microsoft/kiota-serialization-json": "^1.0.0-preview.43",
    "@microsoft/kiota-serialization-multipart": "^1.0.0-preview.22",
    "@microsoft/kiota-serialization-text": "^1.0.0-preview.40",
```

It's gotten a little better, the "data" that's being reported looks now like a full description of the API, though on my end it's heavily cluttered because for some reason Swagger in ASP.NET Core has decided to include every single MIME type under the sun onto every request and I haven't figured out how to panel-beat Swagger into not doing that just yet.

I'm not sure if it's related to the issue, but this is how the error output now looks:

![image](https://github.com/microsoft/kiota-typescript/assets/3036301/aeba9beb-8296-42c5-81df-f4f01faeeb80)

**Comment by Jannik-KJ** [comment]
I'm facing the same issues Error: couldn't find navigation property then data: "{+baseurl}"
Did you find a more common solution? :)

**Comment by baywet** [comment]
(sorry about the breaking changes, we didn't expect so many people to be using typescript generation in kiota yet since it's still an experimental language. But a quick look at packages download stats showed that there's already a lot of people using TypeScript in kiota :) )

**Comment by Jannik-KJ** [comment]
Sounds perfect, looking forward to testing it :)

**Comment by baywet** [comment]
If you want to test things in the meantime, you can use the latest preview.

**Comment by Jannik-KJ** [comment]
i'm on these versions
    "@microsoft/kiota-abstractions": "^1.0.0-preview.44",
    "@microsoft/kiota-authentication-azure": "^1.0.0-preview.39",
    "@microsoft/kiota-http-fetchlibrary": "^1.0.0-preview.43",
    "@microsoft/kiota-serialization-form": "^1.0.0-preview.33",
    "@microsoft/kiota-serialization-json": "^1.0.0-preview.44",
    "@microsoft/kiota-serialization-multipart": "^1.0.0-preview.23",
    "@microsoft/kiota-serialization-text": "^1.0.0-preview.41",

**Comment by jimmywim** [comment]
> (sorry about the breaking changes, we didn't expect so many people to be using typescript generation in kiota yet since it's still an experimental language. But a quick look at packages download stats showed that there's already a lot of people using TypeScript in kiota :) )

Most of those are probably me, I had a headache last week trying to line up the versions of the kiota cli exactly with the versions of the packages correct.

ProTip: Can the npm commands listed with `kiota info` use `-SE` switch instead of `-S` - I got stung wtih the extra `^` character before the version number and npm kept installing the next minor version along.

**Comment by yasaichi** [comment]
For those who will see this issue in the future

As of today with 1.0.0-preview.44 of `kiota-abstractions`, the generated code for create the API client (e.g `createPostsClient`) returns the return value of `apiClientProxifier` implemented in `kiota-abstractions`. The method returns a proxy that throws an error if any property name not included in `paths` of OpenAPI description. That's why you face an error like reported in the issue: `couldn't find navigation property ${any property name} data`. 
One of the hacky ways to avoid this issue is to wrap the proxy returned by `apiClientProxifier` with another proxy:

```ts
const allowedProps = ['onModuleInit', 'then', 'onApplicationBootstrap'];
new Proxy(
  createFakeApiClient(
    new FetchRequestAdapter(
      new AnonymousAuthenticationProvider(),
    ),
  ),
  {
    get: (target, prop) => allowedProps.includes(prop.toString())
      ? undefined
      : Reflect.get(target, prop),
  },
)
```
