### ISSUE TITLE
Is it possible to skip undefined obj from json body? [Typescript]

### ISSUE THREAD

**Issue by illunix** [microsoft/kiota-typescript#1079]
Hey, is it possible to skip undefined obj from json body?

Because right now when I do for example

` const cmd: SignUpCommand = {
      email: this.f.email.value!,
      business: undefined
    };`

it adds `business: {}` to json body but I dont wan't

**Comment by baywet** [comment]
Thanks for reporting this @illunix 
I have transferred your issue to the relevant repository.
If we compare [the dotnet implementation](https://github.com/microsoft/kiota-serialization-json-dotnet/blob/7492e10c9f29cd63c4c3a6115698a9db1fc71896/src/JsonSerializationWriter.cs#L337) with the typescript one, we can see a divergence that would explain this behaviour.
https://github.com/microsoft/kiota-serialization-json-dotnet/blob/7492e10c9f29cd63c4c3a6115698a9db1fc71896/src/JsonSerializationWriter.cs#L337

(see the guard if statement)

Is this something you'd be willing to submit a pull request to address?

**Comment by illunix** [comment]
I don't find myself in this code so rather not @petrhollayms

**Comment by koros** [comment]
Re-opening the issue to ensure edge cases are covered as well since currently its using falsy evaluation to determine which values to skip.

**Comment by koros** [comment]
Fixed by https://github.com/microsoft/kiota-typescript/pull/1133
