### ISSUE TITLE
Request Payload with empty string values ignores all values and send empty object payload

### ISSUE THREAD

**Issue by rners01** [microsoft/kiota-typescript#1129]
Hi,
I'd encountered the issue with empty payload request using kiota generated API client.
Client ignores payload with empty string or undefined values, eg. `property: ""` or `property: undefined`.
Before the request was made I `console.log` my payload and those values were present.

Im thinking potentially the problem could be with the serializer..

My setup:
```Typescript
export function createApiClient(requestAdapter: RequestAdapter) {
    registerDefaultSerializer(JsonSerializationWriterFactory);
    registerDefaultDeserializer(JsonParseNodeFactory);
    if (requestAdapter.baseUrl === undefined || requestAdapter.baseUrl === "") {
        requestAdapter.baseUrl = "https://myrestapi.com";
    }
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<ApiClient>(requestAdapter, pathParameters, ApiClientNavigationMetadata, undefined);
}

// and then...

createApiClient(
    new FetchRequestAdapter(
      new BaseBearerTokenAuthenticationProvider({
        getAuthorizationToken() {
          const token = sessionStorage.getItem(TOKEN_KEY)

          return Promise.resolve(token)
        },
        getAllowedHostsValidator: () => new AllowedHostsValidator(new Set([apiUrl])),
      }),
      undefined,
      new JsonSerializationWriterFactory(),
      KiotaClientFactory.create(window.fetch.bind(window)),
      undefined,
    ),
  )

```

I'm using:
```json
    "@microsoft/kiota-abstractions": "1.0.0-preview.45",
    "@microsoft/kiota-http-fetchlibrary": "1.0.0-preview.44",
    "@microsoft/kiota-serialization-json": "1.0.0-preview.45",
```

**Comment by andrueastman** [comment]
Possibly related to https://github.com/microsoft/kiota-typescript/pull/1120 cc @koros

**Comment by koros** [comment]
Hi @rners01,

Thanks for raising the issue. I would like to seek more clarification; at the moment the serialization step intentionally skips all undefined fields see: https://github.com/microsoft/kiota-typescript/issues/1079, 
e.g
```Typescript
const Item = {
    id: "123"
    name: "Foo",
    serverId: undefined
}
```
In the example above since the `serverId` is undefined, its omitted after serialization. The payload becomes:

```json
{
    "id": "123",
    "name": "Foo"
}
```
Please confirm whether this is what you are seeing on your end and whether it addresses your issue

**Comment by rners01** [comment]
@koros Not really, it skips `""` empty string values in my case too

**Comment by baywet** [comment]
@rners01  thanks for the additional information.
Any chance you could try with the latest version of the kiota dependencies published today? @koros implemented fixes for that specific scenario already.
