### ISSUE TITLE
Dotnet cant convert TimeOnly with 12 numbers in milliseconds

### ISSUE THREAD

**Issue by illunix** [microsoft/kiota-typescript#1202]
Hello, I have issue because dotnet cant parse TimeOnly milliseconds with 12 numbers, from what I tested max numbers of milliseconds is 7.

If you want test it just use TimeOnly type on property in request body and you will see

**Comment by andrueastman** [comment]
Thanks for raising this @illunix 

Any chance you can share more details on the discrepancy? Is it that the kiota libraries for dotnet can't handle the 12 numbers or the language runtime? 
If its the former, would it better to fix in the dotnet side rather than reduce precision here?

**Comment by illunix** [comment]
It is the dotnet side, dotnet can't handle more than 7 digits in milliseconds in TimeOnly @andrueastman
