### ISSUE TITLE
How to add header to all requests?

### ISSUE THREAD

**Issue by illunix** [microsoft/kiota-typescript#1233]
Hello, how can I add custom header that will be included in every request?

**Comment by baywet** [comment]
By implementing a custom handler [like this one](https://github.com/microsoft/kiota-typescript/blob/main/packages/http/fetch/src/middlewares/userAgentHandler.ts)
let us know if you have further questions

**Comment by illunix** [comment]
And then how to use it in my client? Also I just want use accepted-language header so maybe there is any support somewhere?

**Comment by baywet** [comment]
We actually have documentation about that! (we put a lot of efforts filling the documentation gaps recently and it's nice to be able to say that) [See this](https://learn.microsoft.com/en-us/openapi/kiota/middleware), the examples are in CSHarp but if should be easy to transpose.
