### ISSUE TITLE
`Content type application/json does not have a factory registered to be parsed`

### ISSUE THREAD

**Issue by hognevevle** [microsoft/kiota-typescript#1264]
Following an upgrade to 1.16.0, I recently upgraded my app dependencies as instructed by Kiota. 

Previous dependencies in `package.json`:
```
    "@microsoft/kiota-abstractions": "1.0.0-preview.56",
    "@microsoft/kiota-http-fetchlibrary": "1.0.0-preview.55",
    "@microsoft/kiota-serialization-form": "1.0.0-preview.45",
    "@microsoft/kiota-serialization-json": "1.0.0-preview.56",
    "@microsoft/kiota-serialization-multipart": "1.0.0-preview.34",
    "@microsoft/kiota-serialization-text": "1.0.0-preview.53",
```

![CleanShot 2024-07-07 at 19 44 43](https://github.com/microsoft/kiota-typescript/assets/2721188/ab491a46-8585-441a-8e05-f0b2e1cab391)

New dependencies in `package.json`:
```
    "@microsoft/kiota-abstractions": "1.0.0-preview.57",
    "@microsoft/kiota-http-fetchlibrary": "1.0.0-preview.56",
    "@microsoft/kiota-serialization-form": "1.0.0-preview.46",
    "@microsoft/kiota-serialization-json": "1.0.0-preview.57",
    "@microsoft/kiota-serialization-multipart": "1.0.0-preview.35",
    "@microsoft/kiota-serialization-text": "1.0.0-preview.54",
```

Unfortunately, I'm getting the following error after installing the new versions with `yarn`

```
Error: Content type application/json does not have a factory registered to be parsed
    at ParseNodeFactoryRegistry.getRootParseNode (parseNodeFactoryRegistry.ts:38:9)
    at fetchRequestAdapter.ts:374:34
    at async fetchRequestAdapter.ts:188:24
    at async fetchRequestAdapter.ts:166:12
    at async Proxy.init (cart.ts:75:24)
```

Tried deleting node_modules and reinstalling everything, to no avail.

Rolling back to the previous dependency versions does however fix the problem.

**Comment by hognevevle** [comment]
Possibly a duplicate of #1244. Close at will, or let me know if there's additional details I can provide.

**Comment by andrueastman** [comment]
Thanks for raising this @hognevevle 

Any chance you can confirm the workaround provided at https://github.com/microsoft/kiota-typescript/issues/1244 works out for you? If so we can close this so that this can be followed up in that issue....

**Comment by hognevevle** [comment]
Hi @andrueastman , I don't use the Kiota CLI though -- only the VSCode extension. Is there a way to achieve the equivalent of `--serializer none --deserializer none` from the extension? If so I could try that.

**Comment by baywet** [comment]
@hognevevle in the extension it's a setting at this point.

![image](https://github.com/microsoft/kiota-typescript/assets/7905502/32636b7c-b4b9-4560-98d8-98479aa0b90f)
