### ISSUE TITLE
Add release please configuration

### ISSUE THREAD

**Issue by Ndiritu** [microsoft/kiota-typescript#1321]
We want:
 - [ ] release please header file (yaml .github/release-please.yml)
 - [ ] release please manifest (json .release-please-manifest.json)
 - [ ] release please config (json release-please-config.json)
 - [ ] changelog keep a changelog header and unreleased information to be removed
 - [ ] contributing to be updated with commit formatting instructions
 - [ ] delete any version bump scripts
 - [ ] files where the version needs to be updated to be updated with the special comments for release please
 
Sample config: https://github.com/microsoftgraph/msgraph-beta-sdk-java/pull/952

**Comment by baywet** [comment]
for this one the version bump is a bit more complex than other packages.
I usually run the following command

```shell
npx lerna version prerelease --no-private
```

Which also prompts for a confirmation.

**Comment by rkodev** [comment]
@baywet this repo does not have contributing.md and changelog, should I introduce them?

**Comment by baywet** [comment]
Contributing yes, changelog since the versions are not aligned and since we have multiple packages, I'm not sure how one would correlate things. 
I think we should setup release please on this repo for the changelog part
