### ISSUE TITLE
Using number 0 in pathParameters is filtered out

### ISSUE THREAD

**Issue by tobiaswatzek** [microsoft/kiota-typescript#1357]
Hey, thank you for this great library. I did not find any other issues for this.

I was trying it on an existing API that expects numbers for one of the path parameters.
The URL template looks like this `{+baseurl}/api/foo/{someNumber}/records`.
When I pass the parameters `baseurl="https://example.org"` and `someNumber=1` the resulting URL looks like this: `https://example.org/api/foo/1/records`.
If I pass `someNumber=0` the resulting URL is `https://example.org/api/foo//records`. I expect it to be `https://example.org/api/foo/0/records`.

I did some debugging and I think the reason for this issue is the following if-statement in the `RequestInformation` class:

https://github.com/microsoft/kiota-typescript/blob/461795d930cdb3354ea812a79fedc3cdfe9cd066/packages/abstractions/src/requestInformation.ts#L71-L73

If you want, I would be happy to contribute a fix myself. I think one way to handle it would be like the query parameters: 

https://github.com/microsoft/kiota-typescript/blob/461795d930cdb3354ea812a79fedc3cdfe9cd066/packages/abstractions/src/requestInformation.ts#L66-L68.

**Comment by baywet** [comment]
Hi @tobiaswatzek,
Thank you for using kiota and for reaching out.
Thank you for the detailed analysis of the problem, I believe you're correct.
Please go ahead and submit a corrective PR.
