### ISSUE TITLE
guid error: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by marcioatws** [microsoft/kiota-typescript#1467]
Hello, it's me again.

My application uses GUID as the primary key, so I use it constantly. My error may be related to issue https://github.com/microsoft/kiota/issues/4508. However, I think the fix has not yet been applied.

Anyway, I'll report my findings.

I have a "standard" client that gives me an error when performing operations for my service.

For example, I tried using two methods to convert a string to GUID, but the error is the same.

```
const data: CreateProcesso = {
      identificador: this.formGroup.value.identificador!,
      titulo: this.formGroup.value.titulo!,
      fluxogramaXml: this.formGroup.value.fluxogramaXml!,
      fluxogramaSvg: this.formGroup.value.fluxogramaSvg!,
      situacaoId: this.formGroup.value.situacaoId!,
      areaResponsavelId: Guid.parse(this.formGroup.value.areaId!),
      usuarioResponsavelId: parseGuidString(this.formGroup.value.usuarioResponsavelId!),
      descricao: this.formGroup.value.complemento!,
      anexos: this.fileList.filter(x => x.isTransfered && !x.isDeletedUi).map(x => ({ id: x.id, token: x.token }))

   this._kiota.client.api.private.commands.processos.post(data)
      .then(() => this.onSuccess());
    };
```

gives me the following error:

```
hook.js:608  ERROR TypeError: Cannot convert object to primitive value
    at _JsonSerializationWriter.writeGuidValue (jsonSerializationWriter.js:58:30)
    at serializeCreateProcesso (index.ts:2447:16)
    at _JsonSerializationWriter.writeObjectValue (jsonSerializationWriter.js:244:25)
    at requestInformation.js:56:20
    at NoopContextManager2.with (NoopContextManager.js:58:20)
    at ContextAPI2.with (context.js:93:50)
    at NoopTracer2.startActiveSpan (NoopTracer.js:61:23)
    at ProxyTracer2.startActiveSpan (ProxyTracer.js:33:20)
    at _RequestInformation.setContentFromParsable (requestInformation.js:40:53)
    at toRequestInformation (apiClientProxifier.js:44:19)
```

Looking at the error, I noticed that there is a value inside the value in the `this.writeGuidValue` function. Replacing `this.writer.push(`"${value}"`)` with `this.writer.push(`"${value.value}"`` resolved the issue, but I imagine this is not the correct behavior.

**Comment by andrueastman** [comment]
Thanks for raising this @marcioatws 

I believe this will be resolved with the changes in this PR. Keeping this open as this is looked intohttps://github.com/microsoft/kiota-typescript/pull/1475.

**Comment by andrueastman** [comment]
@marcioatws Any chance you can confirm this works for you if you update the dependencies with version `1.0.0-preview.74`? You may also need to rerun generation with the source build at head of the kiota library or wait for the release version tomorrow.

**Comment by marcioatws** [comment]
Hello, @andrueastman!

I followed the procedures you mentioned and apparently everything went well, thank you very much!
