### ISSUE TITLE
Custom header does not exist in response object but exist in response

### ISSUE THREAD

**Issue by illunix** [microsoft/kiota-typescript#1512]
I'm trying to get ``x-forced-sign-out`` header and it does not exist in response body but exist in response, how do i solve it?
![Image](https://github.com/user-attachments/assets/6b7ebbaa-4459-4bce-8012-031584037516)
![Image](https://github.com/user-attachments/assets/15b34eb1-7467-4821-a8a7-91d70df11e63)

**Comment by baywet** [comment]
Hi @illunix 
Thank you for using kiota and for reaching out.

The response headers you're showing seem to be from the CORS pre-flight response and not the actual response.

I don't think there's a way to access the CORS pre-flight headers, this is something the browser does automatically before sending the actual request.

Let us know if you have any additional comments or questions.
