### ISSUE TITLE
Lerna not supported anymore.

### ISSUE THREAD

**Issue by nikithauc** [microsoft/kiota-typescript#175]
Update the mono repo set up to replace lerna.

**Comment by rkodev** [comment]
These are some of the alternatives I have found that can work as an alternative to Learna with the list amount of effort

1. [Rush](https://rushjs.io/)
2. [Yarn WorkSpaces](https://classic.yarnpkg.com/lang/en/docs/workspaces/)
3. [Turbo Repo](https://turborepo.org/)


I'm leaning towards using Rush at the moment

**Comment by nikithauc** [comment]
lerna will suffice for sometime now. Let's wait and see migration trend from lerna.

**Comment by sebastienlevert** [comment]
Lerna is back at being supported! https://github.com/lerna/lerna/issues/3121

**Comment by baywet** [comment]
Closing as learna is now maintained again and we're seeing updates coming through regularly.
