### ISSUE TITLE
typescript core (and generation) should be using UUID

### ISSUE THREAD

**Issue by baywet** [microsoft/kiota-typescript#40]
https://www.npmjs.com/package/uuid or https://www.npmjs.com/package/guid-typescript

https://github.com/microsoft/kiota/blob/47f57ce64af7856d18711f1895dac48d3f1048ae/abstractions/typescript/src/serialization/parseNode.ts#L32
https://github.com/microsoft/kiota/blob/47f57ce64af7856d18711f1895dac48d3f1048ae/serialization/typescript/json/src/jsonParseNode.ts#L16
https://github.com/microsoft/kiota/blob/47f57ce64af7856d18711f1895dac48d3f1048ae/src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs#L85 
[AB#10487](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10487)

**Comment by baywet** [comment]
Ping @nikithauc and @gavinbarron on the matter as I ran into that today again.
guid-typescript is clearly not maintained anymore. There are other alternatives out there.
Currently mapping guids to strings, which is probably subpar.

**Comment by koros** [comment]
Fixed by https://github.com/microsoft/kiota-typescript/pull/745
