### ISSUE TITLE
Case insensitive Records for headers and queryParameters 

### ISSUE THREAD

**Issue by andrueastman** [microsoft/kiota-typescript#618]
Some TODOs exists to have case insensitive records for headers and query parameters

- https://github.com/microsoft/kiota-typescript/blob/0cae35d1b4f758369ed9509740c028b72f04092c/packages/abstractions/src/requestInformation.ts#L76
- https://github.com/microsoft/kiota-typescript/blob/0cae35d1b4f758369ed9509740c028b72f04092c/packages/abstractions/src/requestInformation.ts#L73
- https://github.com/microsoft/kiota-typescript/blob/0cae35d1b4f758369ed9509740c028b72f04092c/packages/abstractions/src/requestInformation.ts#L75

**Comment by baywet** [comment]
also API error needs to be updated too now
