### ISSUE TITLE
Node `TextEncoder` in serialization library causes error in browser environment.

### ISSUE THREAD

**Issue by nikithauc** [microsoft/kiota-typescript#63]
https://github.com/microsoft/kiota-typescript/blob/1d8fc8531793c508c897700572ceaa6e0561cf25/packages/serialization/json/src/jsonParseNodeFactory.ts#L22

The `TextEncoder` used is a node specific and causes issues in the browser.

A fix for this is to an isomorphic way to convert arraybuffer to json.

**Comment by ddyett** [comment]
can we describe the issue more.  How bad is the problem, what is blocked?
