### ISSUE TITLE
Typescript - Custom headers and fetch options configuration

### ISSUE THREAD

**Issue by nikithauc** [microsoft/kiota-typescript#64]
Consider requests such as:

GET https://graph.microsoft.com/v1.0/me/events?$select=subject,body,bodyPreview,organizer,attendees,start,end,location
Prefer: outlook.timezone="Pacific Standard Time"

> https://docs.microsoft.com/en-us/graph/api/user-list-events?view=graph-rest-1.0&tabs=http#request-headers

1. Enable adding custom headers and options
2. Create a configuration object that allows users to customize the request
3. Test similar requests 
[AB#10691](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10691)

**Comment by nikithauc** [comment]
It is relevant.

**Comment by baywet** [comment]
thanks for transferring it for clarity.
