### ISSUE TITLE
Bug: investigate abstractions karma browser test failure  

### ISSUE THREAD

**Issue by nikithauc** [microsoft/kiota-typescript#73]
Test:

 const baseUrl = "https://graph.microsoft.com/v1.0";

    const requestInformation = new RequestInformation();
    requestInformation.pathParameters["baseurl"] = baseUrl;
    requestInformation.urlTemplate = "{+baseurl}/users";
    assert.isNotNull(URL);
    assert.equal(
      requestInformation.URL,
      "https://graph.microsoft.com/v1.0/users"
    );

Error : 
Chrome Headless 100.0.4896.60 (Windows 10) RequestInformation Should set request information uri FAILED                                                                     
        TypeError: Cannot read properties of undefined (reading 'Template')
            at RequestInformation.get URL [as URL] (dist/es/test/index.js:12640:54)
            at Context.<anonymous> (dist/es/test/index.js:12749:41)
Chrome Headless 100.0.4896.60 (Windows 10): Executed 1 of 1 (1 FAILED) (0.011 secs / 0.001 secs)                                                                            
TOTAL: 1 FAILED, 0 SUCCESS

**Comment by rkodev** [comment]
@nikithauc This test is currently passing here https://github.com/microsoft/kiota-typescript/compare/rkodev/investigate-failing-tests

**Comment by sebastienlevert** [comment]
@koros @rkodev  @baywet  Is this something that was already fixed?
