### ISSUE TITLE
Serializing body with string property values in generated POST requests

### ISSUE THREAD

**Issue by jimmywim** [microsoft/kiota-typescript#804]
I have a client generated with Kiota from an OpenAPI file, and several POST methods will send up objects with string value properties, that have all sorts of characters such as newlines, quotes etc.

It seems these string values aren't serialized correctly when making a POST method.

Before kiota, we'd just JSON.stringify the payload and send it up, which would encode string value properties correctly, but it looks like Kiota is writing string value properties verbatim, which breaks the payload and it's no longer valid JSON.

Example:

Say we have an object that we're wanting to POST:

```
const myObj: SomeObjectType = {
  property1: true,
  property2: `This is a "complex" string type with some items on a \r\ndifferent line`
};

await client.api.someController.someAction.post(myObj);
```

Then request will fail as the double quotes and the new line character in that string invalidate the generated JSON.

I've noticed that jsonSerializationWriter does this:

```
    value && this.writer.push(`"${value}"`);
```
https://github.com/microsoft/kiota-typescript/blob/fb4c6848cb05c7d0b5f2aa642776f47103da4860/packages/serialization/json/src/jsonSerializationWriter.ts#L32C5-L32C45

whereas it probably should do this:

```
  value && this.writer.push(JSON.stringify(value));
```

**Comment by baywet** [comment]
Thanks for reporting this! I believe you are correct in your analysis of the problem and in the suggested solution.
We could also take this opportunity to reduce duplication of code and map all the methods that "end up writing strings" to the writeStringValue method (thinking of Date, DateOnly, TimeOnly, Guid...)

Would you be willing to submit a pull request to correct this?

**Comment by jimmywim** [comment]
Sure, can do.
