### ISSUE TITLE
Date property handling

### ISSUE THREAD

**Issue by jimmywim** [microsoft/kiota-typescript#821]
*Im not sure if this is a kiota issue or an issue in my OpenAPI spec generation (i.e. Swagger) - let me know where the true issue lies*

So I have an OpenAPI spec that has models with Date fields, the OpenAPI fragment of the model definition looks like this:

```
...
        "created": {
          "format": "date-time",
          "type": "string"
        },
        "modified": {
          "format": "date-time",
          "type": "string"
        },
...
```

And the server (ASP.NET Core WebAPI) is returning ISO 8601 strings.

The problem I have is that the responses from the server remain as strings when they come through to the generated API client code, which has JS `Date` types.

Thus, when I try to write back to the server I get the error:

```
value.toISOString is not a function
TypeError: value.toISOString is not a function
```

Because the serializer is expecting the types to be of `Date` rather than the strings they've been hydrated with.

I feel this is due to the deserializer not properly handling a model property of type JS `Date` and just using the ISO string returned from the server.

**Comment by baywet** [comment]
Thanks for reporting this. Yes it appears to be a problem with the implementation, especially when comparing [the dotnet implementation](https://github.com/microsoft/kiota-serialization-json-dotnet/blob/23dfc3da6e27fa1b48ca47f890147c73282134ed/src/JsonParseNode.cs#L126)
I've looked at your fix and it looks good to me, please submit that PR.
