### ISSUE TITLE
In failed requests, next to error, return information about the failed request

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/kiota-typescript#873]
In failed requests, next to the error, we should return the information about the failed requests. This will help developers understand which request failed, if they're issuing multiple requests in parallel.

Consider the following scenario: I have several external items queued up that I want to add to a Graph connector. To increase the throughput, I issue several requests in parallel using the following code:

![image](https://github.com/microsoft/kiota-typescript/assets/11164679/053d0121-5a47-4f35-bbd5-558cfbd68ad0)

To avoid blocking the main thread, I'm using promises instead of async/await. The problem is, that because I'm in a loop, by the time I arrive to line 141 where I handle error, the sample object on line 128 is likely referring to another item than the one that failed. This could be saved, if the error object that we throw, contained information about the original request.

Right now, one way to solve it, is to move the Graph call to a separate function to create a closure and persist the information about the request, but it seems like an unnecessary complexity that should be solved by the SDK.

**Comment by sebastienlevert** [comment]
Adding "some" context to this as it's not directly related to kiota-typescript. How we should be thinking of this is that we need this behavior to be baked into the fetch adapter of kiota-typescript, allowing consumers to match the exception with the underlying request that was made. I have a hard time identifying if this is already the case. So @baywet or @koros, can you help us identifying it and make sure this issue is relevant in our case. Thanks!

**Comment by baywet** [comment]
I don't think there's any change to make on kiota typescript (or even the JS SDK) at this point.

Errors could be a map of request id and error instead of an array, the callback line 141 in this example updated, and you'd be able to correlate errors with the sample id or something else if you needed to.

Also: screenshots of code are evil, long live code blocks 😅

**Comment by sebastienlevert** [comment]
In this case, in current kiota-typescript, how do we get the catch to also provide the request id?

**Comment by baywet** [comment]
do you mean the client request id & request id response headers? They are in the error "headers" field

**Comment by waldekmastykarz** [comment]
> Errors could be a map of request id and error instead of an array, the callback line 141 in this example updated, and you'd be able to correlate errors with the sample id or something else if you needed to.

Wouldn't that mean though that I need to keep track of all requests? If so, that sounds like unnecessary effort on the developer side. I'd rather have our SDKs cover the plumbing and let developers focus on building their app.

**Comment by sebastienlevert** [comment]
That would effectively mean that we wouldn't be able to correlate the full request, just it's ID. And you'd need to keep a map of all request-ids and their requests to be able to replay one of the requests. I am leaning with @waldekmastykarz here, where we should be able to have an easy way to discover the underlying request that failed, not just some of its metadata.

**Comment by baywet** [comment]
> > Errors could be a map of request id and error instead of an array, the callback line 141 in this example updated, and you'd be able to correlate errors with the sample id or something else if you needed to.
> 
> Wouldn't that mean though that I need to keep track of all requests? If so, that sounds like unnecessary effort on the developer side. I'd rather have our SDKs cover the plumbing and let developers focus on building their app.

No, the pattern is:
1. set the client request id in the request header
2. capture the errors
3. you're able to correlate requests with their errors looking at the response headers which contains the client request id

**Comment by waldekmastykarz** [comment]
Let's take as an example the use case above: I've got 100 external items I want to upload. I'm using the Graph JS SDK and the only thing I pass is the ID of them item and its payload. The SDK handles everything else for me. I assume it also sets the client request ID for me, right? Or are you saying that I should set it myself? Also, if I were to set a random GUID on each request, how would I know to which request/item the ID corresponds without recording all of them?

**Comment by baywet** [comment]
Yes, the SDK sets it automatically for you unless you set it manually. Giving a new SDK example as this is not the right place to discuss the older SDK.

Lets start with this, which runs one request at a time and blocks (not ideal in terms of perf, but works with your scenario of identifying which request failed)

```TypeScript
const userIds = ["foo", "bar"];
const failures = {};
for(const userId of userIds) {
  try {
    const result = await client.users.byId(userId).get();
    //Do something with the user
  } catch (error) {
    const castError = error as ODataError;
    failures[userId] = castError.message;
  }
```

Now let's optimize a bit
```TypeScript
const userIds = ["foo", "bar"];
const failures = {};
await Promise.all(userIds.map(userId => client.users.byId(userId).get().catch(e => { failures[userId] = (error as ODataError).message; }));
//omitted the then of each result to avoid confusion
```

Optionally you could also pass your own client request id in the get method, and then get it back as the headers on the error to use it as the mapping.

**Comment by waldekmastykarz** [comment]
In the first example, with async, requests will be issued sequentially, so mapping errors to the faulty ID won't be a problem.

In the second example, when we reach the `catch` block, won't the userId be modified and pointing to something else by the time we arrive there?

Also, both examples are simple get requests where the identifier is the ID. How would you map the request if it was a more complex post/patch request? I suspect that you'd need to store it somewhere to be able to debug which is exactly the extra complexity that I was referring to.

**Comment by baywet** [comment]
Why would the user id be modified? It's a parameter of the callback.

If you want to use something else, as I said in my earlier reply, you can pass the client request ID in the request headers and get it back in the error response headers.

**Comment by waldekmastykarz** [comment]
> Why would the user id be modified? It's a parameter of the callback.

I wasn't 100% it would create a closure which is necessary to keep the value in sync with the code in the `catch` block, but if it does then it would work.

Still, it requires developers to keep track of requests and their IDs which seems like an unnecessary complexity that could've been solved in our SDKs, by returning information about the request as part of the error object.

**Comment by baywet** [comment]
> by returning information about the request as part of the error object.

If you mean to include the request body/URL/http action as part of the error, this is just bad design mixing concerns.

As for the response, you already get the response headers and status code today, as well as the deserialized error (when part of the OpenAPI description, which is the case for MSGraph). What else do you need at this point?

**Comment by waldekmastykarz** [comment]
If I'm issuing multiple requests in parallel and one of them fails, I need to see the actual request (URL + headers + body) in order to understand what went wrong. If the only thing I get back is a request ID, it means that I need to build a way to keep track of the request I issued. When using Graph SDKs this is problematic, because Graph SDKs abstract away building requests. While I could track it back to a specific request (eg. based on request ID), unless I can see the exact request that went over the wire, I can't debug the error that I got.

**Comment by baywet** [comment]
> If I'm issuing multiple requests in parallel and one of them fails, I need to see the actual request (URL + headers + body) in order to understand what went wrong

Not with production code, you only "need" this information when debugging your application. For that aspect, multiple solutions exist like the developer proxy, adding a middleware to spy on the requests etc...

**Comment by baywet** [comment]
Yes, we don't want to provide default implementations for those as it'd be easy to end up logging sensitive information in production. People have been bitten by that in the past and we want to avoid giving people a gun to shoot themselves in the foot with.

**Comment by waldekmastykarz** [comment]
@sebastienlevert let's consider extending our conceptual docs with explaining how folks can implement logging enough information both in dev and in their production apps to be able to troubleshoot failed requests while using our SDKs.
