### ISSUE TITLE
Encoding Issue with Polish Characters in Request Payload

### ISSUE THREAD

**Issue by illunix** [microsoft/kiota-typescript#920]
I am experiencing an encoding issue with Polish characters when sending requests. Before sending the request, I verified the value of my string variable by logging it to the console using console.log, and it displayed correctly as "Błonie". However, in the request payload, the variable value is incorrectly encoded as "BBonie". This issue persists with other words containing Polish characters. I am unable to determine the cause of this encoding error.

I have encountered this issue while using TypeScript Client Generator versions v1.8.0-preview.202310260001 and v1.7.0. Any assistance in resolving this encoding issue would be greatly appreciated.

**Comment by illunix** [comment]
I use only typescript for angular client, for rest api c#, and this strings are in request body json @baywet

**Comment by illunix** [comment]
@baywet
`"requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TestProject.Core.Commands.Customers.CreateCustomerCommand"
              }
            }
          }
        }`

**Comment by baywet** [comment]
Thanks for the additional information.
I authored #921 to address this issue.
