### ISSUE TITLE
In the JSON Serializer, arrays at the root of a response are becoming a map

### ISSUE THREAD

**Issue by sebastienlevert** [microsoft/kiota-typescript#978]
Considering this API : https://github.com/thatapicompany/apis/blob/main/theCatAPI.com/thecatapi-oas.yaml

This API returns arrays as the top-most item in the response and not an object with a property to contain the array.

So `[ //.. ]` instead of `{ value: [ //... ] }`.

When getting data from the API, the serialization takes the array but returns it as an object map. In https://github.com/microsoft/kiota-typescript/blob/472c63f1e590458b413f9882e775fa176be05b89/packages/serialization/json/src/jsonParseNode.ts#L66C58-L66C58, it starts with an array:

![image](https://github.com/microsoft/kiota-typescript/assets/7620955/acf96bdf-dc40-4458-9a8f-2b0722fcb176)

But when used with a kiota generated client, it becomes an object

```typescript
      const breedsResult = await catsClient!.breeds.get({ queryParameters: { limit: 10, page: 0 } }) as [];
```

![image](https://github.com/microsoft/kiota-typescript/assets/7620955/6dfd731f-f532-4353-9792-794e5e94ea54)

Something to note, this API doesn't describe its types so the issue might be coming from it.

**Comment by baywet** [comment]
Their [description for the endpoint](https://github.com/thatapicompany/apis/blob/012d5dfb83b789605332e071cdea3c1a12224630/theCatAPI.com/thecatapi-oas.yaml#L1089) describes a response schema of type object.
At glance it looks like the description is misaligned with what the API actually returns.

**Comment by sebastienlevert** [comment]
Closing as implementation differs from the description
