### ISSUE TITLE
Header management should using a Record<String, String>

### ISSUE THREAD

**Issue by sebastienlevert** [microsoft/kiota-typescript#983]
When appending headers to a request, we should be using a familiar approach. Currently, we need to specify a full `Headers` (from `kiota-abstractions`) like this:

```ts
headers: new Headers([['CopnsistencyLevel', new Set(['Eventual'])]]),
```

It should be closer to something like this : 

```ts
headers: { "ConsistencyLevel": "Eventual" }
```

**Comment by baywet** [comment]
this should be changed to Record<string, string[] | string> 
https://github.com/microsoft/kiota-typescript/blob/eb7c7aea28ea2c90efcdab26e0243aa0c58d8890/packages/abstractions/src/requestConfiguration.ts#L12

And related updated should be made

**Comment by sebastienlevert** [comment]
Yes, good point, to support multiple values for the same header.

**Comment by baywet** [comment]
there, #984 addressed that
